networks:
  backend:
    driver: bridge

volumes:
  pg-database:
    driver: local

services:
  ec-cube:
    build: .
    ports:
      - "8080:80"
      - "4430:443"
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://eccube:password@postgres:5432/eccube_db"
      DATABASE_SERVER_VERSION: 15
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:15-alpine
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: eccube_db
      POSTGRES_USER: eccube
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
    volumes:
      - pg-database:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: pg_isready -U eccube -d eccube_db
      interval: 3s
      timeout: 3s
      retries: 10
